package com.altama.forecast.interfaces.web.facade.dto.assembler.c_bpartner;

import com.altama.forecast.domain.c_bpartner.C_bpartner;
import com.altama.forecast.domain.c_bpartner.C_bpartnerBuilder;
import com.altama.forecast.interfaces.web.facade.dto.assembler.IObjectAssembler;
import com.altama.forecast.interfaces.web.facade.dto.c_bpartner.C_bpartnerDTO;
import com.altama.forecast.interfaces.web.facade.dto.c_bpartner.C_bpartnerDTOBuilder;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author admin
 */
public class C_bpartnerDTOAssembler implements IObjectAssembler<C_bpartner, C_bpartnerDTO> {

    @Override
    public C_bpartnerDTO toDTO(C_bpartner domainObject) {
        return new C_bpartnerDTOBuilder()
                .setAcqusitioncost(domainObject.getAcqusitioncost())
                .setActuallifetimevalue(domainObject.getActuallifetimevalue())
                .setAd_client_id(domainObject.getAd_client_id())
                .setAd_language(domainObject.getAd_language())
                .setAd_org_id(domainObject.getAd_org_id())
                .setAd_orgbp_id(domainObject.getAd_orgbp_id())
                .setAlias(domainObject.getAlias())
                .setBpartner_parent_id(domainObject.getBpartner_parent_id())
                .setC_bp_group_id(domainObject.getC_bp_group_id())
                .setC_bpartner_id(domainObject.getBpartner_parent_id())
                .setC_dunning_id(domainObject.getC_dunning_id())
                .setC_greeting_id(domainObject.getC_greeting_id())
                .setC_invoiceschedule_id(domainObject.getC_invoiceschedule_id())
                .setC_paymentterm_id(domainObject.getC_paymentterm_id())
                .setC_paymentterm_invoice_id(domainObject.getC_paymentterm_invoice_id())
                .setC_salesregion_id(domainObject.getC_salesregion_id())
                .setCreated(domainObject.getCreated())
                .setCreatedby(domainObject.getCreatedby())
                .setDeliveryrule(domainObject.getDeliveryrule())
                .setDeliveryviarule(domainObject.getDeliveryviarule())
                .setDescription(domainObject.getDescription())
                .setDistributionmethod(domainObject.getDistributionmethod())
                .setDocumentcopies(domainObject.getDocumentcopies())
                .setDuns(domainObject.getDuns())
                .setFirstsale(domainObject.getFirstsale())
                .setFlatdiscount(domainObject.getFlatdiscount())
                .setFreightcostrule(domainObject.getFreightcostrule())
                .setInterface_flag(domainObject.getInterface_flag())
                .setInvoice_printformat_id(domainObject.getInvoice_printformat_id())
                .setInvoicerule(domainObject.getInvoicerule())
                .setIsactive(domainObject.getIsactive())
                .setIscheckunpaidinvoice(domainObject.getIscheckunpaidinvoice())
                .setIscustomer(domainObject.getIscustomer())
                .setIsdiscountprinted(domainObject.getIsdiscountprinted())
                .setIsdriver(domainObject.getIsdriver())
                .setIsemployee(domainObject.getIsemployee())
                .setIsmechanic(domainObject.getIsmechanic())
                .setIsodt(domainObject.getIsodt())
                .setIsonetime(domainObject.getIsonetime())
                .setIspkp(domainObject.getIspkp())
                .setIsprospect(domainObject.getIsprospect())
                .setIssalesrep(domainObject.getIssalesrep())
                .setIsstopsoht(domainObject.getIsstopsoht())
                .setIssummary(domainObject.getIssummary())
                .setIstaxdelay(domainObject.getIstaxdelay())
                .setIstaxexempt(domainObject.getIstaxexempt())
                .setIsvalid(domainObject.getIsvalid())
                .setIsvendor(domainObject.getIsvendor())
                .setIswarehousestaff(domainObject.getIswarehousestaff())
                .setM_discountschema_id(domainObject.getM_discountschema_id())
                .setM_pricelist_id(domainObject.getM_pricelist_id())
                .setM_shipper_id(domainObject.getM_shipper_id())
                .setMarketsegment(domainObject.getMarketsegment())
                .setNaics(domainObject.getNaics())
                .setName(domainObject.getName())
                .setName2(domainObject.getName2())
                .setNumberemployees(domainObject.getNumberemployees())
                .setPaymentrule(domainObject.getPaymentrule())
                .setPaymentrulepo(domainObject.getPaymentrulepo())
                .setPkpdate(domainObject.getPkpdate())
                .setPo_discountschema_id(domainObject.getPo_discountschema_id())
                .setPo_paymentterm_id(domainObject.getPo_paymentterm_id())
                .setPo_pricelist_id(domainObject.getPo_pricelist_id())
                .setPoreference(domainObject.getPoreference())
                .setPotentiallifetimevalue(domainObject.getPotentiallifetimevalue())
                .setProcessing(domainObject.getProcessing())
                .setRating(domainObject.getRating())
                .setReferenceno(domainObject.getReferenceno())
                .setRingtype(domainObject.getRingtype())
                .setSales_group(domainObject.getSales_group())
                .setSalesrep_2_id(domainObject.getSalesrep_2_id())
                .setSalesrep_id(domainObject.getSalesrep_id())
                .setSalesvolume(domainObject.getSalesvolume())
                .setSendemail(domainObject.getSendemail())
                .setShareofcustomer(domainObject.getShareofcustomer())
                .setShelflifeminpct(domainObject.getShelflifeminpct())
                .setSo_creditlimit(domainObject.getSo_creditlimit())
                .setSo_creditlimit_ht(domainObject.getSo_creditlimit_ht())
                .setSo_creditlimit_pt(domainObject.getSo_creditlimit_pt())
                .setSo_creditused(domainObject.getSo_creditused())
                .setSo_creditused_ht(domainObject.getSo_creditused_ht())
                .setSo_creditused_pt(domainObject.getSo_creditused_pt())
                .setSo_description(domainObject.getSo_description())
                .setSocreditstatus(domainObject.getSocreditstatus())
                .setTaxid(domainObject.getTaxid())
                .setTotalopenbalance(domainObject.getTotalopenbalance())
                .setTrans_code(domainObject.getTrans_code())
                .setUpdated(domainObject.getUpdated())
                .setUpdatedBy(domainObject.getUpdatedBy())
                .setUrl(domainObject.getUrl())
                .setValue(domainObject.getValue())
                .setWmsvalue(domainObject.getWmsvalue())
                .createC_bpartnerDTO();
    }

    @Override
    public C_bpartner toDomain(C_bpartnerDTO dtoObject) {
        return new C_bpartnerBuilder()
                .setAcqusitioncost(dtoObject.getAcqusitioncost())
                .setActuallifetimevalue(dtoObject.getActuallifetimevalue())
                .setAd_client_id(dtoObject.getAd_client_id())
                .setAd_language(dtoObject.getAd_language())
                .setAd_org_id(dtoObject.getAd_org_id())
                .setAd_orgbp_id(dtoObject.getAd_orgbp_id())
                .setAlias(dtoObject.getAlias())
                .setBpartner_parent_id(dtoObject.getBpartner_parent_id())
                .setC_bp_group_id(dtoObject.getC_bp_group_id())
                .setC_bpartner_id(dtoObject.getBpartner_parent_id())
                .setC_dunning_id(dtoObject.getC_dunning_id())
                .setC_greeting_id(dtoObject.getC_greeting_id())
                .setC_invoiceschedule_id(dtoObject.getC_invoiceschedule_id())
                .setC_paymentterm_id(dtoObject.getC_paymentterm_id())
                .setC_paymentterm_invoice_id(dtoObject.getC_paymentterm_invoice_id())
                .setC_salesregion_id(dtoObject.getC_salesregion_id())
                .setCreated(dtoObject.getCreated())
                .setCreatedby(dtoObject.getCreatedby())
                .setDeliveryrule(dtoObject.getDeliveryrule())
                .setDeliveryviarule(dtoObject.getDeliveryviarule())
                .setDescription(dtoObject.getDescription())
                .setDistributionmethod(dtoObject.getDistributionmethod())
                .setDocumentcopies(dtoObject.getDocumentcopies())
                .setDuns(dtoObject.getDuns())
                .setFirstsale(dtoObject.getFirstsale())
                .setFlatdiscount(dtoObject.getFlatdiscount())
                .setFreightcostrule(dtoObject.getFreightcostrule())
                .setInterface_flag(dtoObject.getInterface_flag())
                .setInvoice_printformat_id(dtoObject.getInvoice_printformat_id())
                .setInvoicerule(dtoObject.getInvoicerule())
                .setIsactive(dtoObject.getIsactive())
                .setIscheckunpaidinvoice(dtoObject.getIscheckunpaidinvoice())
                .setIscustomer(dtoObject.getIscustomer())
                .setIsdiscountprinted(dtoObject.getIsdiscountprinted())
                .setIsdriver(dtoObject.getIsdriver())
                .setIsemployee(dtoObject.getIsemployee())
                .setIsmechanic(dtoObject.getIsmechanic())
                .setIsodt(dtoObject.getIsodt())
                .setIsonetime(dtoObject.getIsonetime())
                .setIspkp(dtoObject.getIspkp())
                .setIsprospect(dtoObject.getIsprospect())
                .setIssalesrep(dtoObject.getIssalesrep())
                .setIsstopsoht(dtoObject.getIsstopsoht())
                .setIssummary(dtoObject.getIssummary())
                .setIstaxdelay(dtoObject.getIstaxdelay())
                .setIstaxexempt(dtoObject.getIstaxexempt())
                .setIsvalid(dtoObject.getIsvalid())
                .setIsvendor(dtoObject.getIsvendor())
                .setIswarehousestaff(dtoObject.getIswarehousestaff())
                .setM_discountschema_id(dtoObject.getM_discountschema_id())
                .setM_pricelist_id(dtoObject.getM_pricelist_id())
                .setM_shipper_id(dtoObject.getM_shipper_id())
                .setMarketsegment(dtoObject.getMarketsegment())
                .setNaics(dtoObject.getNaics())
                .setName(dtoObject.getName())
                .setName2(dtoObject.getName2())
                .setNumberemployees(dtoObject.getNumberemployees())
                .setPaymentrule(dtoObject.getPaymentrule())
                .setPaymentrulepo(dtoObject.getPaymentrulepo())
                .setPkpdate(dtoObject.getPkpdate())
                .setPo_discountschema_id(dtoObject.getPo_discountschema_id())
                .setPo_paymentterm_id(dtoObject.getPo_paymentterm_id())
                .setPo_pricelist_id(dtoObject.getPo_pricelist_id())
                .setPoreference(dtoObject.getPoreference())
                .setPotentiallifetimevalue(dtoObject.getPotentiallifetimevalue())
                .setProcessing(dtoObject.getProcessing())
                .setRating(dtoObject.getRating())
                .setReferenceno(dtoObject.getReferenceno())
                .setRingtype(dtoObject.getRingtype())
                .setSales_group(dtoObject.getSales_group())
                .setSalesrep_2_id(dtoObject.getSalesrep_2_id())
                .setSalesrep_id(dtoObject.getSalesrep_id())
                .setSalesvolume(dtoObject.getSalesvolume())
                .setSendemail(dtoObject.getSendemail())
                .setShareofcustomer(dtoObject.getShareofcustomer())
                .setShelflifeminpct(dtoObject.getShelflifeminpct())
                .setSo_creditlimit(dtoObject.getSo_creditlimit())
                .setSo_creditlimit_ht(dtoObject.getSo_creditlimit_ht())
                .setSo_creditlimit_pt(dtoObject.getSo_creditlimit_pt())
                .setSo_creditused(dtoObject.getSo_creditused())
                .setSo_creditused_ht(dtoObject.getSo_creditused_ht())
                .setSo_creditused_pt(dtoObject.getSo_creditused_pt())
                .setSo_description(dtoObject.getSo_description())
                .setSocreditstatus(dtoObject.getSocreditstatus())
                .setTaxid(dtoObject.getTaxid())
                .setTotalopenbalance(dtoObject.getTotalopenbalance())
                .setTrans_code(dtoObject.getTrans_code())
                .setUpdated(dtoObject.getUpdated())
                .setUpdatedBy(dtoObject.getUpdatedBy())
                .setUrl(dtoObject.getUrl())
                .setValue(dtoObject.getValue())
                .setWmsvalue(dtoObject.getWmsvalue())
                .createC_bpartner();
    }

    public List<C_bpartner> toDomain(List<C_bpartnerDTO> arg0) {
        List<C_bpartner> res = new ArrayList<>();
        for (C_bpartnerDTO t : arg0) {
            res.add(new C_bpartnerDTOAssembler().toDomain(t));
        }
        return res;
    }

    public List<C_bpartnerDTO> toDTO(List<C_bpartner> arg0) {
        List<C_bpartnerDTO> res = new ArrayList<>();
        for (C_bpartner t : arg0) {
            res.add(this.toDTO(t));
        }
        return res;
    }

}
