package com.altama.forecast.interfaces.web.facade.dto.assembler.m_product;

import com.altama.forecast.domain.m_product.M_product;
import com.altama.forecast.domain.m_product.M_productBuilder;
import com.altama.forecast.interfaces.web.facade.dto.assembler.IObjectAssembler;
import com.altama.forecast.interfaces.web.facade.dto.m_productDTO.M_productDTO;
import com.altama.forecast.interfaces.web.facade.dto.m_productDTO.M_productDTOBuilder;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author admin
 */
public class M_productDTOAssembler implements IObjectAssembler<M_product, M_productDTO> {

    @Override
    public M_productDTO toDTO(M_product domainObject) {
        return new M_productDTOBuilder()
                .setM_product_id(domainObject.getM_product_id())
                .setAd_client_id(domainObject.getAd_client_id())
                .setAd_org_id(domainObject.getAd_org_id())
                .setIsactive(domainObject.getIsactive())
                .setCreated(domainObject.getCreated())
                .setCreatedby(domainObject.getCreatedby())
                .setUpdated(domainObject.getUpdated())
                .setUpdatedBy(domainObject.getUpdatedBy())
                .setValue(domainObject.getValue())
                .setName(domainObject.getName())
                .setDescription(domainObject.getDescription())
                .setDocumentnote(domainObject.getDocumentnote())
                .setHelp(domainObject.getHelp())
                .setUpc(domainObject.getUpc())
                .setSku(domainObject.getSku())
                .setC_uom_id(domainObject.getC_uom_id())
                .setSalesrep_id(domainObject.getSalesrep_id())
                .setIssummary(domainObject.getIssummary())
                .setIsstocked(domainObject.getIsstocked())
                .setIspurchased(domainObject.getIspurchased())
                .setIssold(domainObject.getIssold())
                .setIsbom(domainObject.getIsbom())
                .setIsinvoiceprintdetails(domainObject.getIsinvoiceprintdetails())
                .setIspicklistprintdetails(domainObject.getIspicklistprintdetails())
                .setIsverified(domainObject.getIsverified())
                .setC_revenuerecognition_id(domainObject.getC_revenuerecognition_id())
                .setM_product_category_id(domainObject.getM_product_category_id())
                .setClassification(domainObject.getClassification())
                .setVolume(domainObject.getVolume())
                .setWeight(domainObject.getWeight())
                .setShelfwidth(domainObject.getShelfwidth())
                .setShelfheight(domainObject.getShelfheight())
                .setShelfdepth(domainObject.getShelfdepth())
                .setUnitsperpallet(domainObject.getUnitsperpallet())
                .setC_taxcategory_id(domainObject.getC_taxcategory_id())
                .setS_resource_id(domainObject.getS_resource_id())
                .setDiscontinued(domainObject.getDiscontinued())
                .setDiscontinuedby(domainObject.getDiscontinuedby())
                .setProcessing(domainObject.getProcessing())
                .setS_expensetype_id(domainObject.getS_expensetype_id())
                .setProducttype(domainObject.getProducttype())
                .setImageurl(domainObject.getImageurl())
                .setDescriptionurl(domainObject.getDescriptionurl())
                .setGuaranteedays(domainObject.getGuaranteedays())
                .setR_mailtext_id(domainObject.getR_mailtext_id())
                .setVersionno(domainObject.getVersionno())
                .setM_attributeset_id(domainObject.getM_attributeset_id())
                .setM_attributesetinstance_id(domainObject.getM_attributesetinstance_id())
                .setDownloadurl(domainObject.getDownloadurl())
                .setM_freightcategory_id(domainObject.getM_freightcategory_id())
                .setM_locator_id(domainObject.getM_locator_id())
                .setGuaranteedaysmin(domainObject.getGuaranteedaysmin())
                .setIswebstorefeatured(domainObject.getIswebstorefeatured())
                .setIsselfservice(domainObject.getIsselfservice())
                .setC_subscriptiontype_id(domainObject.getC_subscriptiontype_id())
                .setIsdropship(domainObject.getIsdropship())
                .setIsexcludeautodelivery(domainObject.getIsexcludeautodelivery())
                .setM_productsubcat_id(domainObject.getM_productsubcat_id())
                .setUser1_id(domainObject.getUser1_id())
                .setIsgeneralsparepart(domainObject.getIsgeneralsparepart())
                .setItem_no(domainObject.getItem_no())
                .setQty_per_innerbox(domainObject.getQty_per_innerbox())
                .setQty_per_ctn(domainObject.getQty_per_ctn())
                .setQty_innerbox_per_ctn(domainObject.getQty_innerbox_per_ctn())
                .setNet_weight(domainObject.getNet_weight())
                .setIsdiscontinued(domainObject.getIsdiscontinued())
                .setNet_weight_dus(domainObject.getNet_weight_dus())
                .setWeight_dus(domainObject.getWeight_dus())
                .setItem_code(domainObject.getItem_code())
                .setPicture(domainObject.getPicture())
                .setIsqi(domainObject.getIsqi())
                .setIsnew(domainObject.getIsnew())
                .setIsnewpo(domainObject.getIsnewpo())
                .setUpdated_2(domainObject.getUpdated_2())
                .setM_productsubcat2_id(domainObject.getM_productsubcat2_id())
                .setM_productsubcat3_id(domainObject.getM_productsubcat3_id())
                .setVolume_ctn(domainObject.getVolume_ctn())
                .setIscashback(domainObject.getIscashback())
                .setWmsvalue(domainObject.getWmsvalue())
                .setC_uom2_id(domainObject.getC_uom2_id())
                .setC_uom3_id(domainObject.getC_uom3_id())
                .setPalletizeby(domainObject.getPalletizeby())
                .setPalletizevalue(domainObject.getPalletizevalue())
                .setMovingtype(domainObject.getMovingtype())
                .setMovingtypesales(domainObject.getMovingtypesales())
                .setInterface_flag(domainObject.getInterface_flag())
                .setWeight_ctn(domainObject.getWeight_ctn())
                .setQtylimitpo(domainObject.getQtylimitpo())
                .setLength_ctn(domainObject.getLength_ctn())
                .setWidth_ctn(domainObject.getWidth_ctn())
                .setHeight_ctn(domainObject.getHeight_ctn())
                .setIslimitpo(domainObject.getIslimitpo())
                .setTier(domainObject.getTier())
                .setQty_ctn_per_pallete(domainObject.getQty_ctn_per_pallete())
                .setHeight_pallete(domainObject.getHeight_pallete())
                .setWeight_pallete(domainObject.getWeight_pallete())
                .setHeight_tier(domainObject.getHeight_tier())
                .setQtylimitoti(domainObject.getQtylimitoti())
                .setIsDiscontinue(domainObject.getIsDiscontinue())
                .createM_productDTO();
    }

    @Override
    public M_product toDomain(M_productDTO dtoObject) {
        return new M_productBuilder()
                .setM_product_id(dtoObject.getM_product_id())
                .setAd_client_id(dtoObject.getAd_client_id())
                .setAd_org_id(dtoObject.getAd_org_id())
                .setIsactive(dtoObject.getIsactive())
                .setCreated(dtoObject.getCreated())
                .setCreatedby(dtoObject.getCreatedby())
                .setUpdated(dtoObject.getUpdated())
                .setUpdatedBy(dtoObject.getUpdatedBy())
                .setValue(dtoObject.getValue())
                .setName(dtoObject.getName())
                .setDescription(dtoObject.getDescription())
                .setDocumentnote(dtoObject.getDocumentnote())
                .setHelp(dtoObject.getHelp())
                .setUpc(dtoObject.getUpc())
                .setSku(dtoObject.getSku())
                .setC_uom_id(dtoObject.getC_uom_id())
                .setSalesrep_id(dtoObject.getSalesrep_id())
                .setIssummary(dtoObject.getIssummary())
                .setIsstocked(dtoObject.getIsstocked())
                .setIspurchased(dtoObject.getIspurchased())
                .setIssold(dtoObject.getIssold())
                .setIsbom(dtoObject.getIsbom())
                .setIsinvoiceprintdetails(dtoObject.getIsinvoiceprintdetails())
                .setIspicklistprintdetails(dtoObject.getIspicklistprintdetails())
                .setIsverified(dtoObject.getIsverified())
                .setC_revenuerecognition_id(dtoObject.getC_revenuerecognition_id())
                .setM_product_category_id(dtoObject.getM_product_category_id())
                .setClassification(dtoObject.getClassification())
                .setVolume(dtoObject.getVolume())
                .setWeight(dtoObject.getWeight())
                .setShelfwidth(dtoObject.getShelfwidth())
                .setShelfheight(dtoObject.getShelfheight())
                .setShelfdepth(dtoObject.getShelfdepth())
                .setUnitsperpallet(dtoObject.getUnitsperpallet())
                .setC_taxcategory_id(dtoObject.getC_taxcategory_id())
                .setS_resource_id(dtoObject.getS_resource_id())
                .setDiscontinued(dtoObject.getDiscontinued())
                .setDiscontinuedby(dtoObject.getDiscontinuedby())
                .setProcessing(dtoObject.getProcessing())
                .setS_expensetype_id(dtoObject.getS_expensetype_id())
                .setProducttype(dtoObject.getProducttype())
                .setImageurl(dtoObject.getImageurl())
                .setDescriptionurl(dtoObject.getDescriptionurl())
                .setGuaranteedays(dtoObject.getGuaranteedays())
                .setR_mailtext_id(dtoObject.getR_mailtext_id())
                .setVersionno(dtoObject.getVersionno())
                .setM_attributeset_id(dtoObject.getM_attributeset_id())
                .setM_attributesetinstance_id(dtoObject.getM_attributesetinstance_id())
                .setDownloadurl(dtoObject.getDownloadurl())
                .setM_freightcategory_id(dtoObject.getM_freightcategory_id())
                .setM_locator_id(dtoObject.getM_locator_id())
                .setGuaranteedaysmin(dtoObject.getGuaranteedaysmin())
                .setIswebstorefeatured(dtoObject.getIswebstorefeatured())
                .setIsselfservice(dtoObject.getIsselfservice())
                .setC_subscriptiontype_id(dtoObject.getC_subscriptiontype_id())
                .setIsdropship(dtoObject.getIsdropship())
                .setIsexcludeautodelivery(dtoObject.getIsexcludeautodelivery())
                .setM_productsubcat_id(dtoObject.getM_productsubcat_id())
                .setUser1_id(dtoObject.getUser1_id())
                .setIsgeneralsparepart(dtoObject.getIsgeneralsparepart())
                .setItem_no(dtoObject.getItem_no())
                .setQty_per_innerbox(dtoObject.getQty_per_innerbox())
                .setQty_per_ctn(dtoObject.getQty_per_ctn())
                .setQty_innerbox_per_ctn(dtoObject.getQty_innerbox_per_ctn())
                .setNet_weight(dtoObject.getNet_weight())
                .setIsdiscontinued(dtoObject.getIsdiscontinued())
                .setNet_weight_dus(dtoObject.getNet_weight_dus())
                .setWeight_dus(dtoObject.getWeight_dus())
                .setItem_code(dtoObject.getItem_code())
                .setPicture(dtoObject.getPicture())
                .setIsqi(dtoObject.getIsqi())
                .setIsnew(dtoObject.getIsnew())
                .setIsnewpo(dtoObject.getIsnewpo())
                .setUpdated_2(dtoObject.getUpdated_2())
                .setM_productsubcat2_id(dtoObject.getM_productsubcat2_id())
                .setM_productsubcat3_id(dtoObject.getM_productsubcat3_id())
                .setVolume_ctn(dtoObject.getVolume_ctn())
                .setIscashback(dtoObject.getIscashback())
                .setWmsvalue(dtoObject.getWmsvalue())
                .setC_uom2_id(dtoObject.getC_uom2_id())
                .setC_uom3_id(dtoObject.getC_uom3_id())
                .setPalletizeby(dtoObject.getPalletizeby())
                .setPalletizevalue(dtoObject.getPalletizevalue())
                .setMovingtype(dtoObject.getMovingtype())
                .setMovingtypesales(dtoObject.getMovingtypesales())
                .setInterface_flag(dtoObject.getInterface_flag())
                .setWeight_ctn(dtoObject.getWeight_ctn())
                .setQtylimitpo(dtoObject.getQtylimitpo())
                .setLength_ctn(dtoObject.getLength_ctn())
                .setWidth_ctn(dtoObject.getWidth_ctn())
                .setHeight_ctn(dtoObject.getHeight_ctn())
                .setIslimitpo(dtoObject.getIslimitpo())
                .setTier(dtoObject.getTier())
                .setQty_ctn_per_pallete(dtoObject.getQty_ctn_per_pallete())
                .setHeight_pallete(dtoObject.getHeight_pallete())
                .setWeight_pallete(dtoObject.getWeight_pallete())
                .setHeight_tier(dtoObject.getHeight_tier())
                .setQtylimitoti(dtoObject.getQtylimitoti())
                .setIsDiscontinue(dtoObject.getIsDiscontinue())
                .createM_product();
    }

    public List<M_product> toDomain(List<M_productDTO> arg0) {
        List<M_product> res = new ArrayList<>();
        for (M_productDTO t : arg0) {
            res.add(new M_productDTOAssembler().toDomain(t));
        }
        return res;
    }

    public List<M_productDTO> toDTO(List<M_product> arg0) {
        List<M_productDTO> res = new ArrayList<>();
        for (M_product t : arg0) {
            res.add(this.toDTO(t));
        }
        return res;
    }

}
